---
# ansible-playbook ansible/init-goaccess.yaml -i '[IP],'

- hosts: all
  remote_user: root
  gather_facts: yes

  tasks:
    - file: path=/var/projects/goaccess/scroll state=directory mode=0755

    - name: Install the gpg key for goaccess
      apt_key:
        url: "https://deb.goaccess.io/gnugpg.key"
        state: present

    - name: Install the goaccess repos
      apt_repository:
        repo: "deb http://deb.goaccess.io/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: install goaccess
      apt: pkg=goaccess state=present update_cache=true

    - cron:
        name: SHELL
        env: yes
        job: /bin/bash

    - cron:
        name: "generate goaccess report"
        minute: "*"
        job: "goaccess -f /var/log/scroll/nginx_access.log
          --keep-last=60
          --ignore-crawlers
          --ignore-status=301
          --ignore-status=302
          --ignore-status=403
          --log-format=COMBINED
          --output /var/projects/goaccess/scroll/index.html"

    - cron:
        name: "generate goaccess monthly report"
        state: absent

    - cron:
        name: "generate goaccess json"
        minute: "*"
        job: "goaccess -f /var/log/scroll/nginx_access.log
          --keep-last=60
          --ignore-statics
          --ignore-crawlers
          --ignore-status=301
          --ignore-status=302
          --ignore-status=403
          --ignore-status=404
          --log-format=COMBINED
          --enable-panel=VISITORS
          --output /var/projects/goaccess/scroll/access.json"
