---
# ansible-playbook ansible/init-goaccess.yaml -i '[IP],'

- hosts: all
  remote_user: root
  gather_facts: yes

  tasks:
    - file: path=/var/projects/goaccess/scroll state=directory mode=0755

    - name: Install the gpg key for goaccess
      apt_key:
        url: "https://deb.goaccess.io/gnugpg.key"
        state: present

    - name: Install the goaccess repos
      apt_repository:
        repo: "deb http://deb.goaccess.io/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: install goaccess
      apt: pkg=goaccess state=present update_cache=true

    - cron:
        name: SHELL
        env: yes
        job: /bin/bash

    - cron:
        name: "generate goaccess report"
        minute: "*"
        job: "goaccess -f /var/log/scroll/nginx_access.log
          --ignore-crawlers
          --ignore-status=301
          --ignore-status=302
          --log-format=COMBINED
          --output /var/projects/goaccess/scroll/index.html"

    - cron:
        name: "generate goaccess monthly report"
        minute: "*"
        job:
          "sed -n '/'$(date '+%d\\/%b\\/%Y' -d '31 day ago')'/,$ p' /var/log/scroll/nginx_access.log | goaccess -
          --ignore-crawlers
          --ignore-status=301
          --ignore-status=302
          --log-format=COMBINED
          --output /var/projects/goaccess/scroll/month.html"

    - cron:
        name: "generate goaccess json"
        minute: "*"
        job:
          "sed -n '/'$(date '+%d\\/%b\\/%Y' -d '31 day ago')'/,$ p' /var/log/scroll/nginx_access.log | goaccess -
          --ignore-statics
          --ignore-crawlers
          --ignore-status=301
          --ignore-status=302
          --ignore-status=404
          --log-format=COMBINED
          --enable-panel=VISITORS
          --output /var/projects/goaccess/scroll/access.json"

    - cron:
        name: "cleanup last month's access logs"
        minute: "16"
        hour: "4"
        day: "25"
        job: |
          awk -i inplace "/"$(date +%b)"/ { print }" /var/log/scroll/nginx_access.log

    - cron:
        name: "cleanup last month's rss logs"
        minute: "16"
        hour: "4"
        day: "25"
        job: |
          awk -i inplace "/"$(date +%b)"/ { print }" /var/log/scroll/nginx_access_rss.log
