---
- hosts: all
  remote_user: root
  gather_facts: yes
  vars:
    NODEJS_VERSION: "14"

  tasks:
    - name: making it confortable
      apt:
        pkg:
          - fish
          - mosh
        state: present

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: install application prereqs
      apt:
        pkg:
          - ffmpeg
          - gcc
          - pkg-config
          - libicu-dev
          - icu-devtools
          - libsqlite3-dev
        state: present

    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/zemlanin/scroll.git"
        dest: /root/scroll

    - name: configure systemd
      copy: src=./scroll.service dest=/lib/systemd/system/scroll.service

    - name: Install deps
      npm:
        path: /root/scroll

    - name: enable app to run on startup
      service: name=scroll.service enabled=yes

    - name: restart app
      service: name=scroll.service state=restarted
