---
# ansible-playbook ansible/init-certbot.yaml -i '[IP],' -e 'cert_email=[EMAIL]'

- hosts: all
  remote_user: root
  gather_facts: no

  tasks:
    - name: install certbot
      apt:
        pkg:
          - software-properties-common
          - certbot
          - python3-certbot-nginx
        state: present

    - name: stop nginx to allow for certbot's server to bind to port 80
      service: name=nginx state=stopped

    - name: get letsencrypt certs
      shell: certbot certonly -q -n -m {{cert_email}} --agree-tos --standalone -d zemlan.in -d www.zemlan.in
      notify: reload nginx

    - service: name=nginx state=started

    - name: set cert auto-renewal
      cron: name="certbot renew"
        job="certbot renew -q --standalone --pre-hook 'systemctl stop nginx' --post-hook 'systemctl start nginx'"
        minute="35"
        hour="4"
        weekday="2,5"

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
