---
- hosts: all
  remote_user: root
  gather_facts: yes
  vars:
    NODEJS_VERSION: "12"

  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: synchronize source
      synchronize:
        src: .
        dest: /root/scroll/
        checksum: yes
        times: no
        recursive: yes
        rsync_opts:
          - "--delete"
          - "--include=posts.db"
          - "--exclude-from=.gitignore"
          - "--exclude=.git/"
          - "--update"

    - name: configure systemd
      copy: src=./scroll.service dest=/lib/systemd/system/scroll.service

    - name: Install deps
      npm:
        path: /root/scroll

    - name: restart app
      service: name=scroll.service state=restarted
